version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: todo-list
    volumes:
      - ./postgres:/var/lib/postgresql/data
